### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by jerodsanto** [Siilikuin/minimum-viable-hugo#5]
Hi Andrew! I'd love to subscribe to your blog, but sadly there's no RSS feed. You should add one!

**Comment by hiAndrewQuinn** [comment]
Your wish is my command. I've set them up a few times in Hugo before - I'll let you know once I've got one I'm happy with now. It'll have to look nice with Miniflux, that's my barometer for quality.

**Comment by hiAndrewQuinn** [comment]
Done! Finally!

@jerodsanto , you'll find the RSS link on the homepage of https://andrew-quinn.me/, right under the title, called "RSS">. The RSS feed was probably [always there, since Hugo is clevererer than me(https://hiandrewquinn.github.io/til-site/posts/hugo-s-secret-rss-feeds/), but I just didn't have a link to it.

**Comment by jerodsanto** [comment]
Cool, subscribed!
